"""New Migration

Revision ID: 556f863b8212
Revises: 
Create Date: 2024-01-24 21:36:09.643558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '556f863b8212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('path', sa.TEXT(), nullable=True),
    sa.Column('query_string', sa.TEXT(), nullable=True),
    sa.Column('fragment', sa.TEXT(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('crawl_times', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'path', 'query_string', 'fragment', name='unique_url')
    )
    op.create_index('urls_index', 'urls', ['domain', 'path', 'query_string', 'fragment'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_urls',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_urls')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('urls_index', table_name='urls')
    op.drop_table('urls')
    # ### end Alembic commands ###
