"""New Migration

Revision ID: d2505c450ee4
Revises: bc7914a7316d
Create Date: 2024-01-25 10:46:14.302220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2505c450ee4'
down_revision = 'bc7914a7316d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_url', 'urls', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_url', 'urls', ['domain', 'path', 'query_string', 'fragment'])
    # ### end Alembic commands ###
