"""New Migration

Revision ID: f7b721eeb3d5
Revises: d2505c450ee4
Create Date: 2024-01-26 22:33:04.926825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b721eeb3d5'
down_revision = 'd2505c450ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('valid_until', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'valid_until')
    # ### end Alembic commands ###
